// Catálogo de juegos de Legans_8 — datos de ejemplo.
// Cada juego: id, nombre, género, plataforma, año, estado, fecha jugado,
// popularidad (para ordenar), destacado, reseña y enlaces a contenido.

const ESTADOS = {
  'completado':  'Completado',
  'en-progreso': 'En progreso',
  'abandonado':  'Abandonado',
  'pendiente':   'Pendiente',
  'multijugador': 'Multijugador',
};

const GAMES = [
  {
    id: 'hollow-knight',
    nombre: 'Hollow Knight',
    genero: 'Metroidvania',
    plataforma: 'PC',
    anio: 2017,
    estado: 'completado',
    jugado: '2025-11-03',
    popularidad: 98,
    destacado: true,
    colores: ['#2D3A6E', '#7C5CFF'],
    portada: 'media/hollow knight portada.jpg',
    resena: [
      'Hallownest me atrapó desde el primer directo. El control es precisísimo y cada zona nueva se siente como abrir un cofre.',
      'Lo terminamos en serie de 9 directos, con el final verdadero incluido. Los jefes opcionales nos hicieron sufrir en chat, pero valió cada intento. Imprescindible si te gusta explorar sin que el juego te lleve de la mano.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'Directo #1 — Empezamos Hollow Knight a ciegas', url: 'https://www.twitch.tv/videos/000000001' },
      { tipo: 'youtube', titulo: 'Serie completa en YouTube (9 partes)', url: 'https://www.youtube.com/playlist?list=PLejemplo1' },
    ],
  },
  {
    id: 'celeste',
    nombre: 'Celeste',
    genero: 'Plataformas',
    plataforma: 'Switch',
    anio: 2018,
    estado: 'completado',
    jugado: '2025-08-14',
    popularidad: 91,
    destacado: true,
    colores: ['#8E3B65', '#FFB4C6'],
    portada: 'media/celeste portada.jpg',
    resena: [
      'La montaña más difícil y más bonita que he subido. Murió el contador de muertes, pero la historia de Madeline lo convierte en algo más que un plataformas exigente.',
      'Las caras B las dejamos para un directo especial que terminó a las 3 de la mañana. El chat no me dejó rendirme.',
    ],
    enlaces: [
      { tipo: 'youtube', titulo: 'Celeste — resumen y opinión final', url: 'https://www.youtube.com/watch?v=ejemplo2' },
    ],
  },
  {
    id: 'elden-ring',
    nombre: 'Elden Ring',
    genero: 'RPG',
    plataforma: 'PS5',
    anio: 2022,
    estado: 'en-progreso',
    jugado: '2026-04-20',
    popularidad: 99,
    destacado: true,
    colores: ['#5C4A1E', '#D4AF37'],
    portada: 'media/Elden ring portada.jpg',
    resena: [
      'La serie actual del canal. Vamos por las Tierras Intermedias sin guía, muriendo con dignidad. Cada directo descubrimos algo que no salía en ningún mapa.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'Serie en directo — martes y jueves', url: 'https://www.twitch.tv/videos/000000003' },
      { tipo: 'youtube', titulo: 'Resúmenes semanales de la serie', url: 'https://www.youtube.com/playlist?list=PLejemplo3' },
    ],
  },
  {
    id: 'stardew-valley',
    nombre: 'Stardew Valley',
    genero: 'Simulación',
    plataforma: 'PC',
    anio: 2016,
    estado: 'en-progreso',
    jugado: '2026-01-10',
    popularidad: 88,
    destacado: false,
    colores: ['#2E6E3A', '#9BE89D'],
    portada: 'media/stardew valley portada.jpg',
    resena: [
      'El juego de los directos tranquilos de domingo. La granja del canal se llama "El Cartucho" y el chat vota qué cultivamos cada temporada.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'Domingos de granja — VODs', url: 'https://www.twitch.tv/videos/000000004' },
    ],
  },
  {
    id: 'silksong',
    nombre: 'Hollow Knight: Silksong',
    genero: 'Metroidvania',
    plataforma: 'PC',
    anio: 2025,
    estado: 'pendiente',
    jugado: null,
    popularidad: 95,
    destacado: false,
    colores: ['#6E2D3A', '#FF8C9E'],
    portada: 'media/silksong portada.jpg',
    resena: [
      'Después de lo que fue Hollow Knight en el canal, Silksong es cita obligada. Está en la lista para la próxima serie larga.',
    ],
    enlaces: [],
  },
  {
    id: 'resident-evil-4',
    nombre: 'Resident Evil 4 Remake',
    genero: 'Terror',
    plataforma: 'PS5',
    anio: 2023,
    estado: 'completado',
    jugado: '2025-10-31',
    popularidad: 93,
    destacado: false,
    colores: ['#3A2D2D', '#C0392B'],
    portada: 'media/resident evil 4 remake.jpg',
    resena: [
      'Lo jugamos entero en el especial de Halloween. Los sustos en directo son otra cosa: el clip del Dr. Salvador persiguiéndome por el pueblo sigue circulando.',
      'Como remake es ejemplar — respeta el original y moderniza justo lo que había que modernizar.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'Especial Halloween — maratón completo', url: 'https://www.twitch.tv/videos/000000006' },
      { tipo: 'youtube', titulo: 'Los 10 mejores sustos del directo', url: 'https://www.youtube.com/watch?v=ejemplo6' },
    ],
  },
  {
    id: 'hades-2',
    nombre: 'Hades II',
    genero: 'Roguelike',
    plataforma: 'PC',
    anio: 2024,
    estado: 'completado',
    jugado: '2025-06-22',
    popularidad: 90,
    destacado: false,
    colores: ['#1E3A5C', '#5CE8E8'],
    portada: 'media/hades 2.jpg',
    resena: [
      'Supergiant lo volvió a hacer. Melinoë tiene un kit completamente distinto a Zagreus y el bucle sigue siendo adictivo. Serie de 6 directos hasta el final verdadero.',
    ],
    enlaces: [
      { tipo: 'youtube', titulo: 'Hades II — serie completa', url: 'https://www.youtube.com/playlist?list=PLejemplo7' },
    ],
  },
  {
    id: 'zelda-totk',
    nombre: 'Zelda: Tears of the Kingdom',
    genero: 'Aventura',
    plataforma: 'Switch',
    anio: 2023,
    estado: 'completado',
    jugado: '2025-03-15',
    popularidad: 97,
    destacado: true,
    colores: ['#2D6E5C', '#A8E8C4'],
    portada: 'media/zelda tear of the kigdom.jpg',
    resena: [
      'Cien horas de directos construyendo máquinas absurdas con Ultrahand. El chat diseñó la mitad de los inventos.',
      'Como secuela de Breath of the Wild me parece superior en casi todo: las profundidades y las islas del cielo le dan una verticalidad que el primero no tenía.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'VODs de la serie completa', url: 'https://www.twitch.tv/videos/000000008' },
      { tipo: 'youtube', titulo: 'Los mejores inventos del chat', url: 'https://www.youtube.com/watch?v=ejemplo8' },
    ],
  },
  {
    id: 'cyberpunk-2077',
    nombre: 'Cyberpunk 2077',
    genero: 'RPG',
    plataforma: 'PC',
    anio: 2020,
    estado: 'abandonado',
    jugado: '2024-09-05',
    popularidad: 80,
    destacado: false,
    colores: ['#3A2D5C', '#F4E04D'],
    portada: 'media/cyberpunk.jpg',
    resena: [
      'Night City es espectacular, pero después de 20 horas la historia no me enganchó lo suficiente para una serie larga. Lo dejamos en pausa indefinida — quizá vuelva con la expansión.',
      'Que quede claro: técnicamente hoy funciona muy bien. Fue cuestión de feeling, no de bugs.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'Primeras horas en Night City', url: 'https://www.twitch.tv/videos/000000009' },
    ],
  },
  {
    id: 'pizza-tower',
    nombre: 'Pizza Tower',
    genero: 'Plataformas',
    plataforma: 'PC',
    anio: 2023,
    estado: 'completado',
    jugado: '2025-05-02',
    popularidad: 78,
    destacado: false,
    colores: ['#6E4A1E', '#FFC857'],
    portada: 'media/pizza tower.jpg',
    resena: [
      'Caos puro en el mejor sentido. La animación estilo cartoon de los 90 y la velocidad lo hacen perfecto para directos: cada nivel es un clip en potencia.',
    ],
    enlaces: [
      { tipo: 'youtube', titulo: 'Pizza Tower en una sentada', url: 'https://www.youtube.com/watch?v=ejemplo10' },
    ],
  },
  {
    id: 'baldurs-gate-3',
    nombre: "Baldur's Gate 3",
    genero: 'RPG',
    plataforma: 'PC',
    anio: 2023,
    estado: 'en-progreso',
    jugado: '2026-02-18',
    popularidad: 96,
    destacado: false,
    colores: ['#4A1E2D', '#E85C8E'],
    portada: 'media/baldur gate 3.jpg',
    resena: [
      'La campaña del canal con decisiones votadas por el chat. Vamos por el acto 2 y ya hemos roto la campaña dos veces. Larian pensó en todo.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'La campaña del chat — VODs', url: 'https://www.twitch.tv/videos/000000011' },
      { tipo: 'youtube', titulo: 'Momentos: el chat elige mal (compilación)', url: 'https://www.youtube.com/watch?v=ejemplo11' },
    ],
  },
  {
    id: 'undertale',
    nombre: 'Undertale',
    genero: 'RPG',
    plataforma: 'PC',
    anio: 2015,
    estado: 'completado',
    jugado: '2024-12-12',
    popularidad: 85,
    destacado: false,
    colores: ['#1E1E3A', '#FFFFFF'],
    portada: 'media/undertale.jpg',
    resena: [
      'Ruta pacifista completa en dos directos. Si no lo has jugado, no leas nada más y juégalo: cuanto menos sepas, mejor. De los pocos juegos que me han hecho sentir culpable por jugar "normal".',
    ],
    enlaces: [
      { tipo: 'youtube', titulo: 'Undertale — reseña sin spoilers', url: 'https://www.youtube.com/watch?v=ejemplo12' },
    ],
  },
  {
    id: 'metroid-dread',
    nombre: 'Metroid Dread',
    genero: 'Metroidvania',
    plataforma: 'Switch',
    anio: 2021,
    estado: 'pendiente',
    jugado: null,
    popularidad: 82,
    destacado: false,
    colores: ['#1E3A3A', '#FF6B35'],
    portada: 'media/metroid dread.jpg',
    resena: [
      'Pendiente para completar la trilogía de metroidvanias del canal junto a Hollow Knight y Silksong. El chat lleva meses pidiéndolo.',
    ],
    enlaces: [],
  },
  {
    id: 'cod-warzone',
    nombre: 'Call of Duty: Warzone',
    genero: 'Shooter',
    plataforma: 'PC',
    anio: 2020,
    estado: 'multijugador',
    jugado: '2026-05-28',
    popularidad: 89,
    destacado: false,
    colores: ['#3A3A2D', '#A8B84A'],
    portada: 'media/warzone caratula.jpg',
    resena: [
      'El battle royale de las noches de squad con el chat y la comunidad. No hay final que completar: cada directo es una nueva caída en Verdansk a ver si esta vez sí ganamos la partida.',
      'Ideal para directos largos y caóticos. Los clips de remontadas imposibles son el pan de cada semana.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'Noches de Warzone con el squad', url: 'https://www.twitch.tv/videos/000000020' },
    ],
  },
  {
    id: 'league-of-legends',
    nombre: 'League of Legends',
    genero: 'MOBA',
    plataforma: 'PC',
    anio: 2009,
    estado: 'multijugador',
    jugado: '2026-06-02',
    popularidad: 92,
    destacado: false,
    colores: ['#1E3A5C', '#C8AA6E'],
    portada: 'media/League of legends.jpg',
    resena: [
      'El MOBA eterno. Lo jugamos en directo aunque suba la presión y baje el ELO. La Grieta del Invocador da para horas de contenido y para que el chat opine de cada pick.',
      'No se completa nunca: es el juego de "una más" que siempre se convierte en cinco más.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'Ranked en directo — camino al ascenso', url: 'https://www.twitch.tv/videos/000000021' },
      { tipo: 'youtube', titulo: 'Las mejores jugadas (y los mejores ragequits)', url: 'https://www.youtube.com/watch?v=ejemplo21' },
    ],
  },
  {
    id: 'straftat',
    nombre: 'STRAFTAT',
    genero: 'Shooter',
    plataforma: 'PC',
    anio: 2024,
    estado: 'multijugador',
    jugado: '2026-04-10',
    popularidad: 71,
    destacado: false,
    colores: ['#3A1E3A', '#FF4FA3'],
    portada: 'media/straftat caratula.webp',
    resena: [
      'Duelos 1v1 rapidísimos al mejor estilo arena shooter. Perfecto para retos con el chat y subs: el que gana se queda, el que pierde rota. Adrenalina pura en partidas de segundos.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'Retos 1v1 contra el chat', url: 'https://www.twitch.tv/videos/000000022' },
    ],
  },
  {
    id: 'fortnite',
    nombre: 'Fortnite',
    genero: 'Shooter',
    plataforma: 'PC',
    anio: 2017,
    estado: 'multijugador',
    jugado: '2026-05-15',
    popularidad: 87,
    destacado: false,
    colores: ['#2D2D6E', '#5CC8FF'],
    portada: 'media/Fortnite.jpg',
    resena: [
      'El battle royale que nunca se queda quieto: cada temporada cambia el mapa, las armas y media comunidad. Lo jugamos en directo para los eventos y para construir cosas imposibles con el chat.',
      'Sin final ni créditos: aquí lo que se persigue es la corona de la victoria magistral.',
    ],
    enlaces: [
      { tipo: 'twitch', titulo: 'Eventos de Fortnite en directo', url: 'https://www.twitch.tv/videos/000000023' },
      { tipo: 'youtube', titulo: 'Construcciones absurdas del chat', url: 'https://www.youtube.com/watch?v=ejemplo23' },
    ],
  },
];

const SOCIALS = [
  { id: 'twitch',    nombre: 'Twitch',      icono: 'TV', color: '#9146FF', url: 'https://www.twitch.tv/legans_8',        desc: 'Directos de lunes a jueves: series largas, especiales con el chat y mucho caos en buena compañía.' },
  { id: 'youtube',   nombre: 'YouTube',     icono: 'YT', color: '#FF0000', url: 'https://www.youtube.com/@legans_8',     desc: 'Series editadas, reseñas sin spoilers y los mejores momentos de los directos.' },
  { id: 'twitter',   nombre: 'X / Twitter', icono: 'X',  color: '#1D9BF0', url: 'https://x.com/legans_8',                desc: 'Avisos de directo, encuestas para elegir el próximo juego y opiniones calientes.' },
  { id: 'instagram', nombre: 'Instagram',   icono: 'IG', color: '#E1306C', url: 'https://www.instagram.com/legans_8',    desc: 'El lado visual: setup, pixel art y memes del canal.' },
  { id: 'discord',   nombre: 'Discord',     icono: 'DC', color: '#5865F2', url: 'https://discordapp.com/users/468571807318933505',            desc: 'La comunidad: recomendaciones de juegos, clips y la campana para no perderte ningún directo.' },
];
